myApp/app/urls.py
from django.conf.urls import include, url
from app import views
urlpatterns = [
    url(r'^$', views.main,name='m'),
]

myApp/myApp/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.static import serve
from myApp.settings import MEDIA_ROOT

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('app.urls', namespace='main')),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
]

myApp/app/models.py
from django.db import models


# Create your models here.

class UserModels(models.Model):
    image = models.ImageField(upload_to="user/%Y/%m", verbose_name=u"Logo", max_length=100)
    name = models.CharField(max_length=20, verbose_name='姓名')
    age = models.IntegerField(verbose_name='年龄', default=0)
    iphone = models.CharField(max_length=11, verbose_name='电话')
    email = models.CharField(max_length=50, verbose_name='邮箱')
    message = models.CharField(max_length=500, verbose_name='个人简介')

    class Meta:
        db_table = 'user'
        verbose_name = verbose_name_plural = '用户'

    def __str__(self):
        return self.name


class ProjectModels(models.Model):
    image = models.ImageField(upload_to="project/%Y/%m", verbose_name=u"Logo", max_length=100)
    test = models.CharField(max_length=500, verbose_name='项目简介')
    url_image = models.ImageField(upload_to="url_image/%Y/%m", verbose_name=u"Logo", max_length=100)
    name = models.CharField(max_length=20, verbose_name='项目名称')

    class Meta:
        db_table = 'project'
        verbose_name = verbose_name_plural = '项目经验'

    def __str__(self):
        return self.name


class CompanyModels(models.Model):
    company_name = models.CharField(max_length=20, verbose_name='公司名称')
    company_image = models.ImageField(upload_to="company/%Y/%m", max_length=100)
    start_time = models.DateField(verbose_name='入职时间')
    end_time = models.DateField(verbose_name='离职时间')

    class Meta:
        db_table = 'company'
        verbose_name = verbose_name_plural = '工作公司'

    def __str__(self):
        return self.company_name


class WorkModels(models.Model):
    company = models.ForeignKey(CompanyModels, verbose_name='公司')
    work = models.CharField(max_length=100, verbose_name='工作职责')

    class Meta:
        db_table = 'work'
        verbose_name = verbose_name_plural = '工作职责'

    def __str__(self):
        return self.work


class SkillModels(models.Model):
    skill_type = models.CharField(max_length=10, choices=(('android', 'Android'), ('python', 'Python')),
                                  default='python',
                                  verbose_name='技能类型')
    skill_test = models.CharField(max_length=200, verbose_name='技能')
    skill_proficiency = models.CharField(max_length=10, choices=(('lj', '了解'), ('sl', '熟练'), ('jt', '精通')),
                                         default='jt',
                                         verbose_name='熟练度')

    class Meta:
        db_table = 'Skill'
        verbose_name = verbose_name_plural = '技能'

    def __str__(self):
        return self.skill_test

myApp/app/views.py
from django.shortcuts import render
from .models import UserModels, ProjectModels, CompanyModels, SkillModels


# Create your views here.

def main(request):
    user = UserModels.objects.all()[0]
    project = ProjectModels.objects.all()
    company = CompanyModels.objects.all()
    skill = SkillModels.objects.all()
    android = skill.filter(skill_type='android')
    python = skill.filter(skill_type='python')
    return render(request, 'app/index.html',
                  {'user': user, 'project': project, 'company': company, 'android': android, 'python': python})

myApp/templates/app/index.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>wlfeng.homepage </title>

    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="pragma" content="no-cache">
    <meta http-equiv="cache-control" content="no-cache">
    <meta http-equiv="expires" content="0">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap-theme.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontAwesome.css' %}">
    <link rel="stylesheet" href="{% static 'css/light-box.css' %}">
    <link rel="stylesheet" href="{% static 'css/templatemo-main.css' %}">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">

    <script src="{% static 'js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
</head>

<body>

<div class="sequence">

    <div class="seq-preloader">
        <svg width="39" height="16" viewBox="0 0 39 16" xmlns="http://www.w3.org/2000/svg"
             class="seq-preload-indicator">
            <g fill="#F96D38">
                <path class="seq-preload-circle seq-preload-circle-1"
                      d="M3.999 12.012c2.209 0 3.999-1.791 3.999-3.999s-1.79-3.999-3.999-3.999-3.999 1.791-3.999 3.999 1.79 3.999 3.999 3.999z"/>
                <path class="seq-preload-circle seq-preload-circle-2"
                      d="M15.996 13.468c3.018 0 5.465-2.447 5.465-5.466 0-3.018-2.447-5.465-5.465-5.465-3.019 0-5.466 2.447-5.466 5.465 0 3.019 2.447 5.466 5.466 5.466z"/>
                <path class="seq-preload-circle seq-preload-circle-3"
                      d="M31.322 15.334c4.049 0 7.332-3.282 7.332-7.332 0-4.049-3.282-7.332-7.332-7.332s-7.332 3.283-7.332 7.332c0 4.05 3.283 7.332 7.332 7.332z"/>
            </g>
        </svg>
    </div>

</div>


<nav>
    {#    <div class="logo">#}
    {#        <img src="{% static 'img/timg.gif' %}" alt="">#}
    {#    </div>#}
    <div class="mini-logo">
        <img src="{% static 'img/mini_logo.png' %}" alt="">
    </div>
    <ul>
        <li><a href="#1"> <em>个人简介</em></a></li>
        <li><a href="#2"> <em>技能展示</em></a></li>
        <li><a href="#3"> <em>工作经验</em></a></li>
        <li><a href="#4"> <em>Android&nbsp;</em></a></li>
        <li><a href="#5"> <em>Python&nbsp;&nbsp;&nbsp;</em></a></li>
    </ul>
</nav>

<div class="slides">
    <div class="slide" id="1">
        <div class="content first-content">
            <div class="container-fluid">
                <div class="col-md-3">
                    <div class="author-image"><img src="{{ MEDIA_URL }}{{ user.image }}" alt=""></div>
                </div>
                <div class="col-md-9">
                    <h2>{{ user.name }}</h2>
                    <p>
                    <p>邮箱：{{ user.email }}</p>
                    <p>电话：{{ user.iphone }}</p>
                    <p>
                        简介：
                        {{ user.message }}
                    </p>
                    </p>
                    {#                    <div class="main-btn"><a href="#2">Read More</a></div>#}
                    {#                    <div class="fb-btn"><a href="#/" target="_blank">Our FB Page</a></div>#}
                </div>
            </div>
        </div>
    </div>
    <div class="slide" id="2">
        <div class="content second-content">
            <div class="container-fluid">
                <div class="col-md-6">
                    <div class="left-content">
                        <h2>Python</h2>
                        {% for python in python %}
                            <p>{{ python.skill_test }}</p>
                        {% endfor %}

                    </div>
                </div>
                <div class="col-md-6">
                    <div class="left-content">
                        <h2>Android</h2>
                        {% for android in android %}
                            <p>{{ android.skill_test }}</p>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="slide" id="3">
        <div class="content third-content">
            <div class="container-fluid">
                <div class="col-md-12">
                    <div class="row">
                        {% for company in company %}

                            <div class="second-section">
                                <div class="container-fluid">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="left-image">
                                                <img src="{{ MEDIA_URL }}{{ company.company_image }}"
                                                     alt="second service">
                                            </div>
                                        </div>
                                        <div class="col-md-6">
                                            <div class="right-content">
                                                <h2>{{ company.company_name }}</h2>
                                                <p>
                                                    工作时间：<br>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                    {{ company.start_time }}-{{ company.end_time }}<br>
                                                    工作职责：<br>
                                                    {% for work in company.workmodels_set.order_by %}
                                                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                                                        {{ work.work }}
                                                        <br>
                                                    {% endfor %}

                                                </p>
                                                {#                                                <div class="main-btn"><a href="#4">Continue Reading</a></div>#}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="slide" id="4">
        <div class="content fourth-content">
            <div class="container-fluid">
                <div class="row">
                    {% for pro in project %}
                        <div class="col-md-4 col-sm-6">
                            <div class="item">
                                <div class="thumb">
                                    <a href="{{ MEDIA_URL }}{{ pro.url_image }}" data-lightbox="image-1"
                                       title='注：该链接来自腾讯bugly'>
                                        <div class="hover-effect">
                                            <div class="hover-content">
                                                <h2>{{ pro.name }}</h2>
                                                <p>{{ pro.test }}</p>
                                            </div>
                                        </div>
                                    </a>
                                    <div class="image">
                                        <img src="{{ MEDIA_URL }}{{ pro.image }}">
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endfor %}


                </div>
            </div>
        </div>
    </div>

    <div class="slide" id="5">
        <div class="content fifth-content">
            <div class="container-fluid">

            </div>
        </div>
    </div>
</div>

<div class="footer">


    <script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
    <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.11.2.min.js"><\/script>')</script>

    <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>

    <script src="{% static 'js/datepicker.js' %}"></script>
    <script src="{% static 'js/plugins.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>

    <script src="http://code.jquery.com/jquery-1.10.2.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function () {



            // navigation click actions
            $('.scroll-link').on('click', function (event) {
                event.preventDefault();
                var sectionID = $(this).attr("data-id");
                scrollToID('#' + sectionID, 750);
            });
            // scroll to top action
            $('.scroll-top').on('click', function (event) {
                event.preventDefault();
                $('html, body').animate({scrollTop: 0}, 'slow');
            });
            // mobile nav toggle
            $('#nav-toggle').on('click', function (event) {
                event.preventDefault();
                $('#main-nav').toggleClass("open");
            });
        });
        // scroll function
        function scrollToID(id, speed) {
            var offSet = 0;
            var targetOffset = $(id).offset().top - offSet;
            var mainNav = $('#main-nav');
            $('html,body').animate({scrollTop: targetOffset}, speed);
            if (mainNav.hasClass("open")) {
                mainNav.css("height", "1px").removeClass("in").addClass("collapse");
                mainNav.removeClass("open");
            }
        }
        if (typeof console === "undefined") {
            console = {
                log: function () {
                }
            };
        }
    </script>
</div>
</body>
</html>